"""add field used for table user

Revision ID: 6ba11b6c18b0
Revises: 767cc9417614
Create Date: 2022-10-24 23:19:21.263850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba11b6c18b0'
down_revision = '767cc9417614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_users', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_users', 'used')
    # ### end Alembic commands ###
