"""add field is_active for account

Revision ID: 767cc9417614
Revises: fbadef91a47e
Create Date: 2022-10-22 15:03:53.560461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767cc9417614'
down_revision = 'fbadef91a47e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_active')
    # ### end Alembic commands ###
