"""add field password

Revision ID: 76b28542f07c
Revises: 7cfa73356a41
Create Date: 2023-01-23 12:40:16.646269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b28542f07c'
down_revision = '7cfa73356a41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_aliases', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_aliases', 'password')
    # ### end Alembic commands ###
