"""update default value for field used

Revision ID: 7cfa73356a41
Revises: 6ba11b6c18b0
Create Date: 2022-10-25 00:30:28.344832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfa73356a41'
down_revision = '6ba11b6c18b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
